### PR TITLE
Remove crossworld connections from dungeonsfull

### PR DESCRIPTION
**Pull request by compiling**

### CODE REVIEW

**Comment by compiling** [comment]
Looks like this introduces a rare failure when rolling inverted dungeonsfull, when Aga Tower goes on top of Hyrule Castle and it tries to put all 3 multi-entrance dungeons in the light world.  Looking into it now.

**Comment by compiling** [comment]
Still a rare problem with the shuffle if Desert/Hyrule Castle goes on Desert East, and Castle Ledge, and Aga Tower is on Castle Ledge (this is a pre-existing problem but is more likely now that there are fewer entrances to choose from).

**Comment by Berserker66** [comment]
Could something be done about the crash chances? Usually I wouldn't mind too much about the occasional abort but with the 255'ers being a thing rerolling is not pleasant.

**Comment by compiling** [comment]
I'm looking into it - basically there are some very basic checks currently to prevent Dark Death Mountain Ledge and Desert Ledge (inverted) connecting to each other, and that needs to be beefed up to handle Hyrule Castle Ledge (inverted), and some crossed / insanity versions of the same issue (Mimic Cave, Bumper Cave Top, Skull Woods).

Fixing this one is going to take a bit longer.

**Comment by compiling** [comment]
Generation is looking solid now.

**Comment by Berserker66** [comment]
Thank you!

**Pull request merged**
